name: Daily Scraper

on:
  schedule:
    - cron: "0 1 * * *" # Runs daily at 01:00 UTC
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run scraper
        run: |
          xvfb-run -a python scrapev2.py

     
      - name: Commit CSV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add export_combined.csv scrape_status.csv || true
          git commit -m "Daily update [skip ci]" || echo "No changes"
          git pull --rebase origin main
          git push

